obj-$(CONFIG_SENSORS_CORE)	+= sensors_core.o

# acclerometer/gyro_sensor
obj-$(CONFIG_SENSORS_LSM6DSL)	+= lsm6dsl_core.o
obj-$(CONFIG_SENSORS_LSM6DSL_I2C)	+= lsm6dsl_i2c.o

# optical_sensor
obj-$(CONFIG_SENSORS_CM36658)	+= cm36658.o
obj-$(CONFIG_SENSORS_CM36657)	+= cm36657.o

# magnetic_sensor
obj-$(CONFIG_SENSORS_YAS539)	+= yas_mag_drv-yas539.o yas_mag_kernel.o

# grip_sensor
obj-$(CONFIG_SENSORS_A96T3X6)	+= a96t3x6.o

